version: '3.3'

services:
  nginx:
    restart: always
    image: nginx
    volumes:
      - /z1s/back/videos:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro      
    ports:
      - 8088:80      
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'

